robot_id = 1
robot_team = "yellow"
onboard_vision_socket_path = "/tmp/ov_socket"

[cp_config]
host = "10.0.64.221"
port = 8192
port_outgoing = 4096

[teensy]
vid = 5824
pid = 1152

[field]
width = 9000
height = 6000
runoff_width = 300
penalty_area_width = 2000
penalty_area_height = 1000
